// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1RTMmsnQMlbCuG_Ri31GMReVffnDwAzk',
    appId: '1:749631499385:web:1e691a752757cf9ae738a8',
    messagingSenderId: '749631499385',
    projectId: 'nkoteng-farm-app',
    authDomain: 'nkoteng-farm-app.firebaseapp.com',
    storageBucket: 'nkoteng-farm-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwVnEvxSJNEyOuvByPGRTDYb5rIG51aA',
    appId: '1:749631499385:android:3d63716a717e1a2de738a8',
    messagingSenderId: '749631499385',
    projectId: 'nkoteng-farm-app',
    storageBucket: 'nkoteng-farm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-kbDxSJyaAUQfkO2_jWzsfyEVl3rDkMs',
    appId: '1:749631499385:ios:4cde1359c6201e90e738a8',
    messagingSenderId: '749631499385',
    projectId: 'nkoteng-farm-app',
    storageBucket: 'nkoteng-farm-app.firebasestorage.app',
    iosBundleId: 'com.nkoteng.nkotengFarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-kbDxSJyaAUQfkO2_jWzsfyEVl3rDkMs',
    appId: '1:749631499385:ios:4cde1359c6201e90e738a8',
    messagingSenderId: '749631499385',
    projectId: 'nkoteng-farm-app',
    storageBucket: 'nkoteng-farm-app.firebasestorage.app',
    iosBundleId: 'com.nkoteng.nkotengFarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1RTMmsnQMlbCuG_Ri31GMReVffnDwAzk',
    appId: '1:749631499385:web:a496667fb37c3563e738a8',
    messagingSenderId: '749631499385',
    projectId: 'nkoteng-farm-app',
    authDomain: 'nkoteng-farm-app.firebaseapp.com',
    storageBucket: 'nkoteng-farm-app.firebasestorage.app',
  );
}
